# e2e/docker-compose.yml from repo
# https://github.com/bahmutov/cypress-open-from-docker-compose
version: '3.2'
services:
 cypress:
   image: cypress/included:5.0.0
   entrypoint: cypress
   # share the current folder as volume to avoid copying
   working_dir: /e2e
   command: run
   volumes:
     - ./:/e2e